-- Migration: Add NLP-processed fields to congress_initiatives table
-- This migration adds fields for accessible titles and NLP metadata

-- Add accessible title field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS accessible_title TEXT;

-- Add NLP subject area field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_subject_area TEXT;

-- Add NLP urgency field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_urgency TEXT CHECK (nlp_urgency IN ('alta', 'media', 'baja'));

-- Add NLP complexity field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_complexity TEXT CHECK (nlp_complexity IN ('alta', 'media', 'baja'));

-- Add NLP readability field (0-100 scale)
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_readability INTEGER CHECK (nlp_readability >= 0 AND nlp_readability <= 100);

-- Add NLP action field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_action TEXT;

-- Add NLP purpose field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_purpose TEXT;

-- Add NLP specific changes field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_specific_changes TEXT;

-- Add NLP regulation scope field
ALTER TABLE public.congress_initiatives 
ADD COLUMN IF NOT EXISTS nlp_regulation_scope TEXT;

-- Add comments to explain the new fields
COMMENT ON COLUMN public.congress_initiatives.accessible_title IS 'Human-readable title generated by NLP processing';
COMMENT ON COLUMN public.congress_initiatives.nlp_subject_area IS 'Subject area identified by NLP (justicia, economia, social, etc.)';
COMMENT ON COLUMN public.congress_initiatives.nlp_urgency IS 'Urgency level detected by NLP (alta, media, baja)';
COMMENT ON COLUMN public.congress_initiatives.nlp_complexity IS 'Complexity level assessed by NLP (alta, media, baja)';
COMMENT ON COLUMN public.congress_initiatives.nlp_readability IS 'Readability score from 0-100 (higher = more readable)';
COMMENT ON COLUMN public.congress_initiatives.nlp_action IS 'Main action verb extracted by NLP (modifica, establece, regula, etc.)';
COMMENT ON COLUMN public.congress_initiatives.nlp_purpose IS 'Purpose of the law extracted by NLP';
COMMENT ON COLUMN public.congress_initiatives.nlp_specific_changes IS 'Specific changes or modifications the law makes';
COMMENT ON COLUMN public.congress_initiatives.nlp_regulation_scope IS 'What the law is actually regulating or changing';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_congress_initiatives_nlp_subject_area 
ON public.congress_initiatives(nlp_subject_area);

CREATE INDEX IF NOT EXISTS idx_congress_initiatives_nlp_urgency 
ON public.congress_initiatives(nlp_urgency);

CREATE INDEX IF NOT EXISTS idx_congress_initiatives_nlp_complexity 
ON public.congress_initiatives(nlp_complexity);

CREATE INDEX IF NOT EXISTS idx_congress_initiatives_nlp_readability 
ON public.congress_initiatives(nlp_readability);

-- Update RLS policies to include new fields
-- (Assuming existing policies allow access to all fields) 